In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [5]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)


Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


In [ ]:
zero=np.zeros((3,4))
print(zero)
print("")
ones=np.ones((2,2))
print(ones)
print("")
ful=np.full((8,6),5)
print(ful)
print('')
random=np.random.random((2,3))
print(random)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1.]
 [1. 1.]]

[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]]

[[0.88154988 0.80190763 0.61555973]
 [0.17884345 0.80038322 0.73463844]]
